#!/usr/bin/env bash

current_window_name() {
    bspc subscribe node_focus | while read -a msg ; do
        printf "T" # Signature of title for the script panel_bar
        xdotool getactivewindow getwindowname
    done
}

clock() {
    while true; do
        printf "S"; # Signature of title for the script panel_bar
        date "+%a %d.%m.%Y %H:%M:%S"; sleep 1;
    done
}

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. "${__dir}/profile"

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

current_window_name > "$PANEL_FIFO" &
clock > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

. ${__dir}/panel_colors

${__dir}/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -u 2 -n "$PANEL_WM_NAME" -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

# Avoid executing xdo before the lemonbar is fully loaded
sleep 0.5

wid=$(xdo id -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
