#!/usr/bin/env bash
# set -x

function get_volume() {
	sink=$1
	pactl list sinks | grep '^[[:space:]]Volume:' | head -n $((sink + 1)) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

function get_default_sink() {
	pactl info | sed -En 's/Default Sink: (.*)/\1/p'
}

function get_sink_id() {
	name=$1
	pactl list sinks | grep "^[[:space:]]Name: $name" -B2 | head -n 1 | sed -e 's/Sink \#//g'
}

# Parse arguments
cmd=${1}
if [ -z "$cmd" ]; then
	echo "Usage: $0 +inc_num% | -dec_num% | abs_num%"
	exit 1
fi
max_volume=${2:-120}

default_sink_id=$(get_sink_id "$(get_default_sink)")

pactl set-sink-volume "${default_sink_id}" "${cmd}"
if [[ $(get_volume "${default_sink_id}") -ge ${max_volume} ]]; then
	pactl set-sink-volume "${default_sink_id}" "${max_volume}%"
fi
