#!/usr/bin/env bash

result=$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')

if [[ -z $result ]]; then
    output=' N/A'
else
    output=" $result"
    color="#00FF00"
fi
echo ${output}
echo ${output}
echo ${color}
exit
