#!/usr/bin/env bash

result=$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')
[[ ! -z $result ]] && output=" $result" && echo ${output} && echo ${output} && echo '#00FF00' && exit
